stages:
- name: split_anatuples
  dependencies: [init]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      data: {step: init, output: data}
      mc: {step: init, output: mc}
      by_playlist: {step: init, output: by_playlist}
      outdir: '{workdir}'
    step: {$ref: 'workflow/steps.yml#/split_anatuples'}
- name: mc_histograms
  dependencies: [split_anatuples]
  scheduler:
    scheduler_type: multistep-stage
    parameters:
      mc_runs: {step: split_anatuples, output: mc_runs}
      mc: {step: init, output: mc}
      index: {step: split_anatuples, output: index}
      outdir: '{workdir}'
      do_truth: 'true'
      do_systematics: 'true'
      signal_def: {step: init, output: signal_def}
      w_exp: {step: init, output: w_exp}
      npi: {step: init, output: npi}
      pim: {step: init, output: pim}
      pi0: {step: init, output: pi0}
    step: {$ref: 'workflow/steps.yml#/mc_histograms'}
    scatter:
      method: zip
      parameters: [index]
- name: merge
  dependencies: [mc_histograms]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      histograms: {stages: 'mc_histograms[*]', output: histograms}
      outdir: '{workdir}'
    step: {$ref: 'workflow/steps.yml#/merge'} 
- name: closure
  dependencies: [merge]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      histograms: {step: merge, output: histograms}
      data_list: {step: split_anatuples, output: data_list}
      mc_list: {step: split_anatuples, output: mc_list}
      data: {step: init, output: data}
      mc: {step: init, output: mc}
      signal_def: {step: init, output: signal_def}
      w_exp: {step: init, output: w_exp}
      npi: {step: init, output: npi}
      pim: {step: init, output: pim}
      pi0: {step: init, output: pi0}
      outdir: '{workdir}'
    step: {$ref: 'workflow/steps.yml#/closure'}