stages:
- name: split_anatuples
  dependencies: [init]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      data: {step: init, output: data}
      mc: {step: init, output: mc}
      by_playlist: {step: init, output: by_playlist}
      outdir: '{workdir}'
    step: {$ref: 'workflow/steps.yml#/split_anatuples'}
- name: test_vars
  dependencies: [split_anatuples]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      mc_list: {step: split_anatuples, output: mc_list}
      mc: {step: init, output: mc}
      data_list: {step: split_anatuples, output: data_list}
      data: {step: init, output: data}
      outdir: '{workdir}'
      signal_def: {step: init, output: signal_def}
      w_exp: {step: init, output: w_exp}
      npi: {step: init, output: npi}
      pim: {step: init, output: pim}
      pi0: {step: init, output: pi0}
    step: {$ref: 'workflow/steps.yml#/test_vars'}