stages:
- name: split_anatuples
  dependencies: [init]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      data: {step: init, output: data}
      mc: {step: init, output: mc}
      outdir: '{workdir}'
    step: {$ref: 'workflow/steps.yml#/split_anatuples'}
- name: make_histograms
  dependencies: [split_anatuples]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      mc_runs: {step: split_anatuples, output: mc_runs}
      mc: {step: init, output: mc}
      outdir: '{workdir}'
      do_truth: {step: init, output: do_truth}
      do_systematics: {step: init, output: do_systematics}
      signal_def: {step: init, output: signal_def}
    step: {$ref: 'workflow/steps.yml#/make_histograms'}
- name: merge_histograms
  dependencies: [make_histograms]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      histograms: {step: make_histograms, output: histograms}
      outdir: '{workdir}'
    step: {$ref: 'workflow/steps.yml#/merge'} 
- name: xsec_calculation
  dependencies: [merge_histograms]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      histograms: {step: merge_histograms, output: histograms}
      data_list: {step: split_anatuples, output: data_list}
      mc_list: {step: split_anatuples, output: mc_list}
      data: {step: init, output: data}
      mc: {step: init, output: mc}
      signal_def: {step: init, output: signal_def}
      outdir: '{workdir}'
    step: {$ref: 'workflow/steps.yml#/xsec_calculation'} 
- name: plot
  dependencies: [xsec_calculation]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      xsec: {step: xsec_calculation, output: xsec}
      data_list: {step: split_anatuples, output: data_list}
      mc_list: {step: split_anatuples, output: mc_list}
      data: {step: init, output: data}
      mc: {step: init, output: mc}
      do_truth: {step: init, output: do_truth}
      do_systematics: {step: init, output: do_systematics}
      signal_def: {step: init, output: signal_def}
      outdir: '{workdir}'
    step: {$ref: 'workflow/steps.yml#/plot'}